ecomapp/urls.py
from django.urls import path
from .views import *

app_name = 'ecomapp'
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>", ProductDetailView.as_view(), name="productdetail"),
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    
    path("register/", CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(), name="customerorderdetail"),
    path("Search/", SearchView.as_view(), name="search"),
    

    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(), name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order/<int:pk>-change/", AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),


    path("admin-product/list/", AdminProductListView.as_view(), name="adminproductlist"),

    path("admin-product/add/", AdminProductCreateView.as_view(), name="adminproductcreate"),


    


]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls"),)
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)
    
    def __str__(self):
        return self.user.username



class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name



class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True) 
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField()
    description = models.TextField()
    warrantly = models.CharField(max_length=300, null=True, blank=True)
    return_policy = models.CharField(max_length=300, null=True, blank=True)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title





class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True) 
    total = models.PositiveIntegerField(default=0)     
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)
       


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartProduct: " + str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("khalti", "khalti"),
    ("Esewa", "Esewa"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    Order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False, null=True, blank=True)
    



    def __str__(self):
        return "Order: " + str(self.id)

templates/about.html
{% extends 'base.html' %} {% block content %} {% block title %}About{% endblock %}
<h1>We are the emerging ecommerce in the city.</h1>
{% endblock %}

templates/addtocart.html
{% extends 'base.html' %} {% block title %}Add To Cart{% endblock %} {% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %} {% block title %}All Products{% endblock %} {% block content %}
<div class="container">
    <h3>All Products</h3>
    <hr> {% for cat in allcategories %}
    <h4>{{cat.title}}</h4>
    <hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3">
            <div class="m-4">
                <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit:cover;">
                <p class="mt-3">Price: <strike> Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>

    <div class="">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'ecomapp:home' %}">
                <a href="#"><img style="height: 30px;" src="{% static 'image/urubuzzLogo.jpg' %}" alt=""></a>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Cart</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            My Account
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if request.user.customer %}
                            <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                            <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a> {% else %}
                            <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a> |
                            <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a> {% endif %}
                        </div>
            </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
                <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search"
                    aria-label="Search" required>
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>

        </nav>
    </div>
    {% block content %} {% endblock %}


    <div class="">
        <section class="footer-section">
            <div class="container">

                <hr>
                <hr>
                <div class="row">
                    <div class="col-lg-8 col-sm-6">
                        <div class="footer-widget about-widget">
                            <h2>About</h2>
                            <p>
                                Selling products through an online shop is the best way to make a bit of extra money.
                                Customer feedback can not only help improve products, but also increase conversions. At
                                Softimpact, we develop innovative and creative products and services that provide
                                total communication and information solutions. Among a plethora of services, web design
                                and development, tailor made applications, ERPs, CRMs, e-commerce solutions,
                                business-to-business applications, business-to-client
                                applications, managed hosting and internet portal management are few that we offer.
                                Satisfied clients around the globe bear testimony to the quality of our work. </p>
                            <img src="{% static 'image/cards.png' %}" alt="">
                        </div>
                    </div>


                    <div class="col-lg-3 col-sm-6">
                        <div class="footer-widget contact-widget">
                            <h2></h2>
                            <div class="con-info">
                                <span>C.</span>
                                <p>URU software solution </p>
                            </div>
                            <div class="con-info">
                                <span>B.</span>
                                <p>Silicon city Inodre, 452011, P.O. BOX 68 </p>
                            </div>
                            <div class="con-info">
                                <span>T.</span>
                                <p>+91 810388XXXX</p>
                            </div>
                            <div class="con-info">
                                <span>E.</span>
                                <p>urusoftwaresolution@yahoo.com</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="social-links-warp">
                <div class="container">
                    <div class="social-links">
                        <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                        <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                        <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                        <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                        <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                        <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    </div>

                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    <p class="text-white text-center mt-5">Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This WebApp is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="#9399868779" target="_blank">URUss</a></p>
                    <p class="text-white text-center mt-5">Copyright &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

                </div>
            </div>
        </section>
    </div>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.zoom.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %} {% block title %} Checkout {% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Items in the cart</h3>
            <a href="{% url 'ecomapp:mycart' %}">Update Cart</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %} {{form.as_p}}
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contactus.html
{% extends 'base.html' %} {% block content %} {% block title %} Contact us{% endblock %}
<h1>To Contact us, Call the following numbers</h1>
<p>8839184058</p>
<p>9898989898</p>
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %} {% block title %}My Profile{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="cil-md-4">
            <h3>Detail Information</h3>
            <hr>
            <p><span class="font-weight-bold">Name: </span> {{customer.full_name}}</p>
            <p><span class="font-weight-bold">Username: </span> {{customer.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span> {{customer.user.email}}</p>
            <p><span class="font-weight-bold">Address: </span> {{customer.address}}</p>
            <p><span class="font-weight-bold">Joined on: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Previous Orders</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Order ID</th>
                        <th>Amount</th>
                        <th>Ordered on</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk %}">#ORDER_{{ord.id}}</a></td>
                        <td>{{ord.total}}</td>
                        <td>{{ord.created_at|timesince}} age</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %} {% block title %}Customer Registration {% endblock %} {% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3>
            <form action="" method="POST">
                {% csrf_token %} {{form.as_p}}
                <button class="btn btn-primary">Register as a Customer</button>
            </form>
            <p> Already have an account? </p><a href="{% url 'ecomapp:customerlogin' %}">Login here</a>
        </div>
    </div>
</div>
{% endblock %}

templates/esewarequest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #myform {
            display: none;
        }
    </style>
</head>

<body>
    <h3 style="text-align: center;">You will be redirected to the esewa website..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="hidden">
        <input value="{{order.total}}" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="epay_payment" name="scd" type="hidden">
        <input value="order_{{order.id}}" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/esewa-verify/" type="hidden" name="su">
        <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
        <input value="Submit" type="submit">
    </form>

    <script>
        setTimeout(function() {
            document.getElementById("myform").submit()
        }, 500)
    </script>
</body>

</html>

templates/home.html
{% extends 'base.html' %} {% load static %} {% block title %}Home{% endblock %} {% block content %}
<div class="">
    <hr>
    <section class="hero-section">
        <div class="hero-slider owl-carousel">
            <div class="hs-item set-bg" data-setbg="{% static 'image/uj1.jpg' %}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-7 text-white">
                            <span>Lovely</span>
                            <h2>My Fashion</h2>
                            <p>Fashion means something that is trendy or valued in a certain time period.The prevailing fashion/ trends/style is called ‘vogue’. The way we talk, the words that we use while talking, the voice tone, the clothing, the way we
                                wear the clothes, etc. are all aspects of fashion.</p>

                        </div>
                    </div>
                    <div class="offer-card text-white">
                        <span> from </span>
                        <h2>0-M</h2>
                        <p>Place bid</p>
                    </div>
                </div>
            </div>
            <div class="hs-item set-bg" data-setbg="{% static 'image/uj3.jpg' %}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-6 col-lg-7 text-white">
                            <span>Lovely</span>
                            <h2>My Fashion</h2>
                            <p>Fashion means something that is trendy or valued in a certain time period.The prevailing fashion/ trends/style is called ‘vogue’. The way we talk, the words that we use while talking, the voice tone, the clothing, the way we
                                wear the clothes, etc. are all aspects of fashion.</p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="slide-num-holder" id="snh-1"></div>
        </div>
    </section>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3 card">
            <div class="m-4">
                <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                <p class="mt-3">Price: <strike> Rs. {{p.marked_price}}</strike> Rs. {{p.selling_price}}</p>
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Previous</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            {% endif %} {% for i in product_list.paginator.page_range %} {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %} {% endfor %} {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Next</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

templates/mycart.html
{% extends 'base.html' %} {% block title %}My Cart{% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <h4>Items in my cart</h4>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/productdetail.html
{% extends 'base.html' %} {% block title %}{{product.title}}{% endblock %} {% block content %}
<div class="container">
    <div class="product-section">
        <h3>Product: {{product.title}}</h3>
        <hr>
        <div class="row">
            <div class="col-md-5">
                <div class="product-pic-zoom" style="height: 400px;">
                    <img class="product-big-img" src="{{product.image.url}}" alt="">
                </div>
                <div class="product-thumbs" tabindex="1" style="overflow: hidden; outline: none;">
                    <div class="product-thumbs-track">
                        <div class="pt " data-imgbigurl="{{product.image.url}}"><img src="{{product.image.url}}" alt=""></div>
                        {% for pi in product.productimage_set.all %}
                        <div class="pt " data-imgbigurl="{{pi.image.url}}"><img src="{{pi.image.url}}" alt=""></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-5">
                <h4>{{product.title}}> (Viewed {{product.view_count}} times)</h4>
                <h5>Category: {{product.category}}</h5>
                <h5>Price: <strike>Rs. {{product.marked_price}}</strike> Rs. {{product.selling_price}}</h5>
                <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-info">Add To Cart</a>
                <hr>
                <p class="text-info">Warrantly: {{product.warrantly}}</p>
                <p class="text-info">Return Policy: {{product.return_policy}}</p>
                <hr>
                <p>{{product.description}}</p>
            </div>
        </div>
    </div>
    {% endblock %}

templates/search.html
{% extends 'base.html' %} {% block title %}Search {% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Search Results for <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr> {% for result in results %}
            <div class="row">
                <div class="col-md-4">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-8">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    <p>Return Policu:{{result.return_policy}}</p>
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Add To Cart</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}